=== lauriiShii/LENGUAJE-DE-MARCAS/segundo trimestre/DTD/Ejercicios/ejercicio04.dtd
<!ELEMENT alumnos (alumno)>
<!ELEMENT alumno (nombre, telefono, email?, direccion, faltas?, notas?)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>

<!ELEMENT faltas (faltasJustificadas?, faltasInjustificadas?)>
<!ELEMENT fatasJustificadas (#PCDATA)>
<!ELEMENT faltasInjustificadas (#PCDATA)>
<!ELEMENT notas (#PCDATA)>

<!ATTLIST alumno dni ID #REQUIRED>

<!ELEMENT modulos (modulo)>
<!ELEMENT modulo (nombre, numHoras, caracter, fecha)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT numhoras (#PCDATA)>
<!ELEMENT caracter (opcional|obligatorio)>
<!ELEMENT opcional EMPTY>
<!ELEMENT obligatorio EMPTY>
<!ELEMENT fecha (#PCDATA)>

<!ATTLIST modulo id ID #REQUIRED>

=== lauriiShii/LENGUAJE-DE-MARCAS/segundo trimestre/DTD/Ejercicios/ejercicio04.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos SYSTEM "ejercicio04.dtd">

<alumnos>
	<alumno dni="16965696L">
		<nombre>Ana Fernandez Gutierrez</nombre>
		<telefono>789654321</telefono>
		<email>ana.fdezgtrrez@hotmail.com,</email>
		<direccion>C/ El Percebe, 13 de Santander CP 39302</direccion>
	</alumno>
	<alumno dni="98765432H">
		<nombre>Pepito Grillo</nombre>
		<telefono>656566555</telefono>
		<email>yhyh@yahoo.com,</email>
		<direccion>Avd. El Pez, 5 de Suances CP 39401</direccion>
		<notas>apto</notas>
	</alumno>
</alumnos>
<modulos id="1">
	<nombre>Lenguaje de marcas</nombre>
	<numHoras>4</numHoras>
	<caracter>obligatorio</caracter>
	<fecha>15/09/2010 a 30/06/2011</fecha>
</modulos>
