=== lauriiShii/LENGUAJE-DE-MARCAS/segundo trimestre/DTD/Ejercicios/ejercicio03.dtd
<!ELEMENT personas (persona+)>
<!ELEMENT persona (nombre, nacimiento, genero, direccion+)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nacimiento EMPTY>
<!ELEMENT genero EMPTY>

<!ELEMENT direccion (provincia, poblacion, cpostal, calle)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT cpostal (#PCDATA)>
<!ELEMENT calle (#PCDATA)>

<!ATTLIST persona id ID #REQUIRED>
<!ATTLIST nacimiento dia CDATA #REQUIRED>
<!ATTLIST nacimiento mes CDATA #REQUIRED>
<!ATTLIST nacimiento anio CDATA #REQUIRED>
<!ATTLIST genero sexo (Hombre|Mujer) #REQUIRED>

=== lauriiShii/LENGUAJE-DE-MARCAS/segundo trimestre/DTD/Ejercicios/ejercicio03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas SYSTEM "ejercicio03.dtd">

<personas>
	<persona id="1">
		<nombre>Pablo</nombre>
		<nacimiento dia="11" mes="10" anio="1999"/>
		<genero sexo="hombre"/>
		<direccion>
			<provincia>huelva</provincia>
			<poblacion>Valverde</poblacion>
			<cpostal>11111</cpostal>
			<calle>jardines</calle>
		</direccion>
	</persona>
	<persona id="2">
		<nombre>Sara</nombre>
		<nacimiento dia="10" mes="05" anio="1980"/>
		<genero sexo="mujer"/>
		<direccion>
			<provincia>Granada</provincia>
			<poblacion>Motril</poblacion>
			<cpostal>22221</cpostal>
			<calle>rosales</calle>
		</direccion>
	</persona>
</personas>
